simple:
	go run simple.go
anonymous_func:
	go run anonymous_func.go
anonymous_func_2:
	go run anonymous_func_2.go
waitgroup:
	go run waitgroup.go
waitgroup_2:
	go run waitgroup_2.go
waitgroup_3:
	go run waitgroup_3.go
callback:
	go run callback.go
callback_2:
	go run callback_2.go
mutex:
	go run mutex.go
channel:
	go run channel.go
channel_2:
	go run channel_2.go
buffered_channel:
	go run buffered_channel.go
directional:
	go run directional.go
select_statement:
	go run select_statement.go
ranging:
	go run ranging.go