simple:
	go run simple.go
anonymous_func:
	go run anonymous_func.go
anonymous_func_2:
	go run anonymous_func_2.go
waitgroup:
	go run waitgroup.go
waitgroup_2:
	go run waitgroup_2.go
waitgroup_3:
	go run waitgroup_3.go
callback:
	go run callback.go
callback_2:
	go run callback_2.go
mutex:
	go run mutex.go